name: GH-200 CoHack
on: push
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say namaste
        run: echo "hello namaste"

      - name: Checkout src code
        uses: actions/checkout@v6

      - name: list files
        run: ls -la

      - name: Generate ASCII Art
        run:  |
          sudo apt-get install -y figlet
          figlet "GH-200 CoHack"
          figlet -f slant " Git hub actions"

      - name: Run shell script
        run:  |
          chmod +x ./scripts/welcome.sh
          bash ./scripts/welcome.sh
  
